frase = 'Curso em Vídeo Python'
# print(frase)
# print(frase[3])
# print(frase[3:13])
# print(frase[:13])
# print(frase[13:])
# print(frase[9::3])
# print(frase[9:12:1])
# print(frase.count('o'))
print(frase.upper().count('o'))
# print(len(frase))
# print(frase.replace('Python','Android'))
