a = int (input('A tabuada de qual  número  você gostaria de saber? '))
tabuada = a * 1
tabuada2 = a * 2
tabuada3 = a * 3
tabuada4 = a * 4
tabuada5 = a * 5
tabuada6 = a * 6
tabuada7 = a * 7
tabuada8 = a * 8
tabuada9 = a * 9
tabuada10 = a * 10
print('1 x {} = {}'.format(a,tabuada))
print('2 x {} = {}'.format(a,tabuada2))
print('3 x {} = {}'.format(a,tabuada3))
print('4 x {} = {}'.format(a,tabuada4))
print('5 x {} = {}'.format(a, tabuada5))
print('6 x {} = {}'.format(a,tabuada6))
print('7 x {} = {}'.format(a, tabuada7))
print('8 x {} = {}'.format(a, tabuada8))
print('9 x {} = {}'.format(a, tabuada9))
print('10 x {} = {}'.format(a, tabuada10))
